package:
  name: pyllelic
  version: 0.2.8

source:
  path: ./..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - biopython
    - bismark
    - numpy
    - openpyxl
    - pandas
    - plotly
    - pysam
    - python >=3.8
    - scipy
    - tqdm
    - xlrd
    - xlsxwriter

test:
  imports:
    - pyllelic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Paradoxdruid/pyllelic
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Paradoxdruid
