repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [--strict, --ignore-missing-imports]
        files: ^(pyllelic/|tests/)
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        files: ^(pyllelic/|tests/)
