name: pyllelic
channels:
  - paradoxdruid
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pandas>=2.1.0
  - python=3.10
  - biopython
  - pyllelic
  - ipywidgets
  - notebook
  - numpy>=1.21.1
  - seaborn
  - dask
