{% set name = "pyllelic" %}{% set version = "0.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Paradoxdruid/pyllelic/archive/v0.2.7.tar.gz
  sha256: ae90df840dd499d9fa594512852709c6270c109169f6ad9b1630287ae21b4bb7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - biopython
    - bismark
    - numpy
    - openpyxl
    - pandas
    - plotly
    - pysam
    - python >=3.8
    - scipy
    - tqdm
    - xlrd
    - xlsxwriter

test:
  imports:
    - pyllelic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Paradoxdruid/pyllelic
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Paradoxdruid
